version: '3.8'

services:
  flask-server:
    image: academic-team-management-flask:latest
    build: ./server
    env_file:
      - .env
    ports:
      - ${FLASK}:5000
    args:
      - PRIVATE_KEY=${PRIVATE_KEY}
  react-server:
    image: academic-team-management-react:latest
    build: 
      context: ./client
      args:
        - APP=${FLASK}
    env_file:
      - .env
    ports:
      - ${REACT}:3000
    depends_on:
      - flask-server
  mongodb:
    image: mongo
    container_name: mongodb
    restart: unless-stopped
    environment:
    - PUID={PUID}
    - PGID={PGID}
    - MONGODB_INITDB_ROOT_USERNAME={MONGODB_INITDB_ROOT_USERNAME}
    ports:
    - ${MONGO}:27017
