name: "Mongo Scheduled Backup"
on:
  schedule:
    - cron: "0 */5 * * *"
jobs:
  Trigger-backup:
    runs-on: ubuntu-latest
    steps:
      - name: DisplayTestBackup
        run: echo "Hello I work on a schedule"
